language: go

go:
- tip

install:
- GO111MODULE=on go mod vendor
- wget -O - -q https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.11.3

script:
- go test -v -cover -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)